[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TOMAS"
authors = [{name = "Qiuyu Lian", email = "qiuyu.lian@sjtu.edu.cn"}]
dynamic = ["version", "description"]
